import type { InterpretationResult } from './types';
// Fix: Import the 'Formula' enum to resolve reference errors.
import { Formula, Sex } from './types';

export const QTC_THRESHOLDS: Record<Sex, { normal: number; borderline: number }> = {
  [Sex.Male]: {
    normal: 450,
    borderline: 470,
  },
  [Sex.Female]: {
    normal: 460,
    borderline: 480,
  },
};

export const QTC_LOWER_THRESHOLD = 350;

export const FORMULA_DESCRIPTIONS: Record<Formula, string> = {
  [Formula.Bazett]: 'En yaygın formül, ancak kalp hızı < 60 veya > 100 ise hatalıdır. Formül: QT / √RR.',
  [Formula.Fredericia]: 'Yüksek kalp hızlarında daha isabetlidir. Formül: QT / (RR^(1/3)).',
  [Formula.Framingham]: 'QT ve RR arasındaki doğrusal ilişkiyi dikkate alır. Formül: QT + 0.154 * (1 - RR).',
  [Formula.Hodges]: 'Kalp hızına dayalı doğrusal bir formüldür. Formül: QT + 1.75 * (HR - 60).',
};

export const INTERPRETATION_MAP: Record<InterpretationResult['level'], { className: string; message: string }> = {
  'Normal': { className: 'text-green-800 bg-green-100', message: 'QTc normal aralıkta.' },
  'Sınırda': { className: 'text-yellow-800 bg-yellow-100', message: 'QTc sınırda uzamış. Klinik korelasyon önerilir.' },
  'Uzamış': { className: 'text-red-800 bg-red-100', message: 'QTc uzamış. Bu durum aritmi riskini artırabilir.' },
  'Kısa': { className: 'text-orange-800 bg-orange-100', message: 'QTc kısa. Bu durumun da klinik önemi olabilir.' },
  'Geçersiz': { className: 'text-slate-600 bg-slate-100', message: 'Yorumu görmek için değerleri girin.' },
};

export const DRUG_LIST: { generic: string; brand: string }[] = [
  { generic: 'Abarelix (PR)', brand: 'Plenaxis' },
  { generic: 'Abiraterone (CR)', brand: 'Zytiga and others' },
  { generic: 'Aclarubicin (KR)', brand: 'Aclacin and others' },
  { generic: 'Adagrasib (PR)', brand: 'Krazati' },
  { generic: 'Albuterol (salbutamol) (SR)', brand: 'Proventil and others' },
  { generic: 'Alfuzosin (PR)', brand: 'Uroxatral' },
  { generic: 'Alimemazine (Trimeprazine) (PR)', brand: 'Nedeltran and others' },
  { generic: 'Amantadine (CR)', brand: 'Symmetrel and others' },
  { generic: 'Amiodarone (KR)', brand: 'Cordarone and others' },
  { generic: 'Amisulpride (CR)', brand: 'Barhemsys and others' },
  { generic: 'Amitriptyline (CR)', brand: 'Elavil (Discontinued 6/13) and others' },
  { generic: 'Amphetamine (Amfetamine) (SR)', brand: 'Adderal-XR and others' },
  { generic: 'Amphotericin B (CR)', brand: 'Fungilin and others' },
  { generic: 'Amsacrine (Acridinyl anisidide) (CR)', brand: 'Amsidine' },
  { generic: 'Anagrelide (KR)', brand: 'Agrylin and others' },
  { generic: 'Apalutamide (PR)', brand: 'Erleada' },
  { generic: 'Apomorphine (PR)', brand: 'Apokyn and others' },
  { generic: 'Arformoterol (SR)', brand: 'Brovana' },
  { generic: 'Aripiprazole (PR)', brand: 'Abilify and others' },
  { generic: 'Arsenic trioxide (KR)', brand: 'Trisenox' },
  { generic: 'Artemether/Lumefantrine (PR)', brand: 'Coartem' },
  { generic: 'Artenimol/piperaquine (PR)', brand: 'Eurartesim' },
  { generic: 'Asenapine (PR)', brand: 'Saphris and others' },
  { generic: 'Astemizole (KR)', brand: 'Hismanal' },
  { generic: 'Atazanavir (CR)', brand: 'Reyataz and others' },
  { generic: 'Atomoxetine (PR)', brand: 'Strattera' },
  { generic: 'Azithromycin (KR)', brand: 'Zithromax and others' },
  { generic: 'Bedaquiline (PR)', brand: 'Sirturo' },
  { generic: 'Bendamustine (PR)', brand: 'Treanda and others' },
  { generic: 'Bendroflumethiazide (Bendrofluazide) (CR)', brand: 'Aprinox and others' },
  { generic: 'Benzphetamine (SR)', brand: 'Didrex and others' },
  { generic: 'Bepridil (KR)', brand: 'Vascor' },
  { generic: 'Betrixaban (PR)', brand: 'Bevyxxa' },
  { generic: 'Bicalutamide (PR)', brand: 'Casodex' },
  { generic: 'Bilastine (PR)', brand: 'Allertine and others' },
  { generic: 'Bortezomib (Bortexomib) (PR)', brand: 'Velcade and others' },
  { generic: 'Bosutinib (PR)', brand: 'Bosulif' },
  { generic: 'Buprenorphine (PR)', brand: 'Butrans and others' },
  { generic: 'Cabozantinib (PR)', brand: 'Cometriq' },
  { generic: 'Capecitabine (PR)', brand: 'Xeloda' },
  { generic: 'Carbetocin (PR)', brand: 'Pabal and others' },
  { generic: 'Ceritinib (PR)', brand: 'Zykadia' },
  { generic: 'Cesium Chloride (KR)', brand: 'Energy Catalyst' },
  { generic: 'Chloral hydrate (CR)', brand: 'Aquachloral and others' },
  { generic: 'Chloroquine (KR)', brand: 'Aralen' },
  { generic: 'Chlorpromazine (KR)', brand: 'Thorazine and others' },
  { generic: 'Chlorprothixene (KR)', brand: 'Truxal' },
  { generic: 'Cilostazol (KR)', brand: 'Pletal' },
  { generic: 'Cimetidine (CR)', brand: 'Tagamet' },
  { generic: 'Ciprofloxacin (KR)', brand: 'Cipro and others' },
  { generic: 'Cisapride (KR)', brand: 'Propulsid' },
  { generic: 'Citalopram (KR)', brand: 'Celexa and others' },
  { generic: 'Clarithromycin (KR)', brand: 'Biaxin and others' },
  { generic: 'Clofazimine (CR)', brand: 'Lamprene' },
  { generic: 'Clomipramine (CR)', brand: 'Anafranil' },
  { generic: 'Clotiapine (PR)', brand: 'Entumine' },
  { generic: 'Clozapine (PR)', brand: 'Clozaril and others' },
  { generic: 'Cobimetinib (PR)', brand: 'Cotellic' },
  { generic: 'Cocaine (KR)', brand: 'Cocaine' },
  { generic: 'Crizotinib (PR)', brand: 'Xalkori' },
  { generic: 'Cyamemazine (Cyamepromazine) (PR)', brand: 'Tercian' },
  { generic: 'Dabrafenib (PR)', brand: 'Tafinlar' },
  { generic: 'Dasatinib (PR)', brand: 'Sprycel' },
  { generic: 'Degarelix (PR)', brand: 'Firmagon and others' },
  { generic: 'Delamanid (PR)', brand: 'Deltyba' },
  { generic: 'Desipramine (PR)', brand: 'Pertofrane and others' },
  { generic: 'Dexmedetomidine (PR)', brand: 'Precedex and others' },
  { generic: 'Dexmethylphenidate (SR)', brand: 'Focalin and others' },
  { generic: 'Dextroamphetamine (Dexamfetamine) (SR)', brand: 'Dexedrine and others' },
  { generic: 'Dextromethorphan/Quinidine (PR)', brand: 'Nuedexta' },
  { generic: 'Diethylpropion (amfepramone) (SR)', brand: 'Tenuate and others' },
  { generic: 'Diltiazem (CR)', brand: 'Cardizem' },
  { generic: 'Diphenhydramine (CR)', brand: 'Benadryl and others' },
  { generic: 'Disopyramide (KR)', brand: 'Norpace' },
  { generic: 'Dobutamine (SR)', brand: 'Dobutrex' },
  { generic: 'Dofetilide (KR)', brand: 'Tikosyn' },
  { generic: 'Dolasetron (PR)', brand: 'Anzemet' },
  { generic: 'Domperidone (KR)', brand: 'Motilium and others' },
  { generic: 'Donepezil (KR)', brand: 'Aricept' },
  { generic: 'Dopamine (SR)', brand: 'Intropine' },
  { generic: 'Doxepin (CR)', brand: 'Sinequan and others' },
  { generic: 'Dronedarone (KR)', brand: 'Multaq' },
  { generic: 'Droperidol (KR)', brand: 'Inapsine and others' },
  { generic: 'Droxidopa (SR)', brand: 'Northera' },
  { generic: 'Efavirenz (PR)', brand: 'Sustiva' },
  { generic: 'Eliglustat (PR)', brand: 'Cerdelga' },
  { generic: 'Encorafenib (PR)', brand: 'Braftovi' },
  { generic: 'Entrectinib (PR)', brand: 'Rozlytrek' },
  { generic: 'Eperisone (CR)', brand: 'Myonal and others' },
  { generic: 'Ephedrine (SR)', brand: 'Rynatuss and others' },
  { generic: 'Epinephrine (Adrenaline) (SR)', brand: 'Primatene and others' },
  { generic: 'Epirubicin (PR)', brand: 'Ellence and others' },
  { generic: 'Eribulin mesylate (PR)', brand: 'Halaven' },
  { generic: 'Erythromycin (KR)', brand: 'E.E.S. and others' },
  { generic: 'Escitalopram (KR)', brand: 'Cipralex and others' },
  { generic: 'Esomeprazole (CR)', brand: 'Nexium and others' },
  { generic: 'Ezogabine (Retigabine) (PR)', brand: 'Potiga and others' },
  { generic: 'Famotidine (CR)', brand: 'Pepcid and others' },
  { generic: 'Felbamate (PR)', brand: 'Felbatol' },
  { generic: 'Fenfluramine (SR)', brand: 'Fintepla' },
  { generic: 'Fenoterol (SR)', brand: 'Berotec and others' },
  { generic: 'Fexinidazole (PR)', brand: 'Fexinidazole' },
  { generic: 'Fingolimod (PR)', brand: 'Gilenya' },
  { generic: 'Flecainide (KR)', brand: 'Tambocor and others' },
  { generic: 'Fluconazole (KR)', brand: 'Diflucan and others' },
  { generic: 'Fluorouracil (5-FU) (PR)', brand: 'Adrucil and others' },
  { generic: 'Fluoxetine (CR)', brand: 'Prozac and others' },
  { generic: 'Flupentixol (PR)', brand: 'Depixol and others' },
  { generic: 'Fluticasone And Salmeterol (SR)', brand: 'Advair and others' },
  { generic: 'Fluvoxamine (CR)', brand: 'Faverin and others' },
  { generic: 'Formoterol (SR)', brand: 'Foradil and others' },
  { generic: 'Furosemide (frusemide) (CR)', brand: 'Lasix and others' },
  { generic: 'Galantamine (CR)', brand: 'Reminyl and others' },
  { generic: 'Garenoxacin (CR)', brand: 'Geninax' },
  { generic: 'Gatifloxacin (KR)', brand: 'Tequin' },
  { generic: 'Gemifloxacin (PR)', brand: 'Factive' },
  { generic: 'Gepirone (PR)', brand: 'Exxua' },
  { generic: 'Gepotidacin (PR)', brand: 'Blujepa' },
  { generic: 'Gilteritinib (PR)', brand: 'Xospata' },
  { generic: 'Givinostat (PR)', brand: 'Duvyzat' },
  { generic: 'Glasdegib (PR)', brand: 'Daurismo' },
  { generic: 'Granisetron (PR)', brand: 'Kytril and others' },
  { generic: 'Grepafloxacin (KR)', brand: 'Raxar' },
  { generic: 'Halofantrine (KR)', brand: 'Halfan' },
  { generic: 'Haloperidol (KR)', brand: 'Haldol and others' },
  { generic: 'Hydrochlorothiazide (CR)', brand: 'Apo-Hydro and others' },
  { generic: 'Hydrocodone - ER (PR)', brand: 'Hysingla™ ER and others' },
  { generic: 'Hydroquinidine (Dihydroquinidine) (KR)', brand: 'Serecor' },
  { generic: 'Hydroxychloroquine (KR)', brand: 'Plaquenil and others' },
  { generic: 'Hydroxyzine (CR)', brand: 'Atarax and others' },
  { generic: 'Ibogaine (KR)', brand: 'N/A' },
  { generic: 'Ibutilide (KR)', brand: 'Corvert' },
  { generic: 'Iloperidone (PR)', brand: 'Fanapt and others' },
  { generic: 'Imatinib (PR)', brand: 'Gleevec and others' },
  { generic: 'Imipramine (Melipramine) (PR)', brand: 'Tofranil' },
  { generic: 'Indacaterol (SR)', brand: 'Arcapta Neohaler and others' },
  { generic: 'Indapamide (CR)', brand: 'Lozol and others' },
  { generic: 'Inotuzumab ozogamicin (PR)', brand: 'Besponsa' },
  { generic: 'Isoflurane (PR)', brand: 'Forane' },
  { generic: 'Isoproterenol (isoprenaline) (SR)', brand: 'Medihaler-Iso and others' },
  { generic: 'Isradipine (PR)', brand: 'Dynacirc' },
  { generic: 'Itraconazole (CR)', brand: 'Sporanox and others' },
  { generic: 'Ivabradine (KR)', brand: 'Procoralan and others' },
  { generic: 'Ivosidenib (PR)', brand: 'Tibsovo' },
  { generic: 'Ketanserin (PR)', brand: 'Sufrexal' },
  { generic: 'Ketoconazole (CR)', brand: 'Nizoral and others' },
  { generic: 'Lacidipine (PR)', brand: 'Lacipil and others' },
  { generic: 'Lansoprazole (CR)', brand: 'Prevacid and others' },
  { generic: 'Lapatinib (PR)', brand: 'Tykerb and others' },
  { generic: 'Lefamulin (PR)', brand: 'Xenleta' },
  { generic: 'Lenvatinib (PR)', brand: 'Lenvima' },
  { generic: 'Leuprolide (Leuprorelin) (PR)', brand: 'Lupron and others' },
  { generic: 'Levalbuterol (Levsalbutamol) (SR)', brand: 'Xopenex and others' },
  { generic: 'Levofloxacin (KR)', brand: 'Levaquin and others' },
  { generic: 'Levoketoconazole (PR)', brand: 'Recorlev' },
  { generic: 'Levomepromazine (Methotrimeprazine) (KR)', brand: 'Nosinan and others' },
  { generic: 'Levomethadone (levamethadone) (PR)', brand: 'N/A' },
  { generic: 'Levomethadyl acetate (KR)', brand: 'Orlaam' },
  { generic: 'Levomethamphetamine (Levmetamfetamine) (SR)', brand: 'Sinu Inhaler and others' },
  { generic: 'Levosulpiride (KR)', brand: 'Lesuride and others' },
  { generic: 'Lisdexamfetamine (SR)', brand: 'Vyvanse' },
  { generic: 'Lithium (PR)', brand: 'Eskalith and others' },
  { generic: 'Lofexidine (PR)', brand: 'Lucemyra' },
  { generic: 'Loperamide (CR)', brand: 'Imodium' },
  { generic: 'Lopinavir/Ritonavir (PR)', brand: 'Kaletra and others' },
  { generic: 'Lumateperone (PR)', brand: 'Caplyta' },
  { generic: 'Lurasidone (PR)', brand: 'Latuda' },
  { generic: 'Macimorelin (PR)', brand: 'Macrilen' },
  { generic: 'Maprotiline (PR)', brand: 'Ludiomil' },
  { generic: 'Mavorixafor (PR)', brand: 'Xolremdi' },
  { generic: 'Meglumine antimoniate (KR)', brand: 'Glucantime' },
  { generic: 'Melperone (PR)', brand: 'Bunil and others' },
  { generic: 'Mesoridazine (KR)', brand: 'Serentil' },
  { generic: 'Metaproterenol (Orciprenaline) (SR)', brand: 'Metaprel and others' },
  { generic: 'Methadone (KR)', brand: 'Dolophine and others' },
  { generic: 'Methamphetamine (Metamfetamine) (SR)', brand: 'Desoxyn and others' },
  { generic: 'Methylphenidate (SR)', brand: 'Ritalin and others' },
  { generic: 'Metoclopramide (CR)', brand: 'Reglan and others' },
  { generic: 'Metolazone (CR)', brand: 'Zytanix and others' },
  { generic: 'Metronidazole (CR)', brand: 'Flagyl and others' },
  { generic: 'Mianserin (PR)', brand: 'Tolvon' },
  { generic: 'Midodrine (SR)', brand: 'ProAmatine and others' },
  { generic: 'Midostaurin (PR)', brand: 'Rydapt' },
  { generic: 'Mifepristone (PR)', brand: 'Korlym and others' },
  { generic: 'Mirabegron (PR)', brand: 'Myrbetriq' },
  { generic: 'Mirtazapine (PR)', brand: 'Remeron' },
  { generic: 'Mobocertinib (KR)', brand: 'Exkivity' },
  { generic: 'Moclobemide (PR)', brand: 'Amira and others' },
  { generic: 'Motixafortide (PR)', brand: 'Aphexda' },
  { generic: 'Moxifloxacin (KR)', brand: 'Avelox and others' },
  { generic: 'Necitumumab (PR)', brand: 'Portrazza' },
  { generic: 'Nelfinavir (CR)', brand: 'Viracept' },
  { generic: 'Nicardipine (PR)', brand: 'Cardene' },
  { generic: 'Nifekalant (KR)', brand: 'Shinbit' },
  { generic: 'Nilotinib (PR)', brand: 'Tasigna' },
  { generic: 'Norepinephrine (SR)', brand: 'Levophed' },
  { generic: 'Norfloxacin (PR)', brand: 'Noroxin and others' },
  { generic: 'Nortriptyline (PR)', brand: 'Pamelor and others' },
  { generic: 'Nusinersen (PR)', brand: 'Spinraza' },
  { generic: 'Ofloxacin (PR)', brand: 'Floxin' },
  { generic: 'Olanzapine (CR)', brand: 'Zyprexa and others' },
  { generic: 'Oliceridine (PR)', brand: 'Olinvyk' },
  { generic: 'Olodaterol (SR)', brand: 'Striverdi Respimat' },
  { generic: 'Omeprazole (CR)', brand: 'Losec and others' },
  { generic: 'Ondansetron (KR)', brand: 'Zofran and others' },
  { generic: 'Opipramol (PR)', brand: 'Deprenil and others' },
  { generic: 'Osilodrostat (PR)', brand: 'Isturisa' },
  { generic: 'Osimertinib (KR)', brand: 'Tagrisso' },
  { generic: 'Oxaliplatin (KR)', brand: 'Eloxatin' },
  { generic: 'Oxymetazoline (SR)', brand: 'Afrin and others' },
  { generic: 'Oxytocin (PR)', brand: 'Pitocin and others' },
  { generic: 'Ozanimod (PR)', brand: 'Zeposia' },
  { generic: 'Pacritinib (PR)', brand: 'Vonjo' },
  { generic: 'Paliperidone (PR)', brand: 'Invega and others' },
  { generic: 'Palonosetron (PR)', brand: 'Aloxi' },
  { generic: 'Panobinostat (PR)', brand: 'Farydak' },
  { generic: 'Pantoprazole (CR)', brand: 'Protonix and others' },
  { generic: 'Papaverine HCl (Intra-coronary) (KR)', brand: 'ParaTime SR and others' },
  { generic: 'Paroxetine (CR)', brand: 'Paxil and others' },
  { generic: 'Pasireotide (PR)', brand: 'Signifor' },
  { generic: 'Pazopanib (PR)', brand: 'Votrient' },
  { generic: 'Pentamidine (KR)', brand: 'Pentam' },
  { generic: 'Perphenazine (PR)', brand: 'Trilafon and others' },
  { generic: 'Phendimetrazine (SR)', brand: 'Bontril and others' },
  { generic: 'Phentermine (SR)', brand: 'Adipex P and others' },
  { generic: 'Phenylephrine (SR)', brand: 'Neosynephrine' },
  { generic: 'Phenylpropanolamine (SR)', brand: 'Acutrim and others' },
  { generic: 'Pilsicainide (PR)', brand: 'Sunrythm' },
  { generic: 'Pimavanserin (PR)', brand: 'Nuplazid' },
  { generic: 'Pimozide (KR)', brand: 'Orap' },
  { generic: 'Pipamperone (PR)', brand: 'Dipiperon and others' },
  { generic: 'Piperacillin/Tazobactam (CR)', brand: 'Tazosyn and others' },
  { generic: 'Pitolisant (Tiprolisant) (PR)', brand: 'Wakix' },
  { generic: 'Ponesimod (PR)', brand: 'Ponvory' },
  { generic: 'Posaconazole (CR)', brand: 'Noxafil and others' },
  { generic: 'Pralsetinib (PR)', brand: 'Gavreto' },
  { generic: 'Pretomanid (PR)', brand: 'Dovprela' },
  { generic: 'Primaquine phosphate (PR)', brand: 'Jasoprim and others' },
  { generic: 'Probucol (KR)', brand: 'Lorelco' },
  { generic: 'Procainamide (KR)', brand: 'Pronestyl and others' },
  { generic: 'Promethazine (PR)', brand: 'Phenergan' },
  { generic: 'Propafenone (CR)', brand: 'Rythmol SR and others' },
  { generic: 'Propofol (KR)', brand: 'Diprivan and others' },
  { generic: 'Prothipendyl (PR)', brand: 'Dominal and others' },
  { generic: 'Pseudoephedrine (SR)', brand: 'PediaCare and others' },
  { generic: 'Quetiapine (CR)', brand: 'Seroquel' },
  { generic: 'Quinidine (KR)', brand: 'Quinaglute and others' },
  { generic: 'Quinine sulfate (CR)', brand: 'Qualaquin and others' },
  { generic: 'Quizartinib (KR)', brand: 'Vanflyta' },
  { generic: 'Ranolazine (CR)', brand: 'Ranexa and others' },
  { generic: 'Relugolix (PR)', brand: 'Orgovyx and others' },
  { generic: 'Remdesivir (PR)', brand: 'Veklury' },
  { generic: 'Remimazolam (PR)', brand: 'Byfavo' },
  { generic: 'Revumenib (PR)', brand: 'Revuforj' },
  { generic: 'Ribociclib (PR)', brand: 'Kisqali' },
  { generic: 'Rilpivirine (PR)', brand: 'Edurant and others' },
  { generic: 'Risperidone (CR)', brand: 'Risperdal' },
  { generic: 'Ritodrine (SR)', brand: 'Yutopar' },
  { generic: 'Rivastigmine (PR)', brand: 'Exelon' },
  { generic: 'Romidepsin (PR)', brand: 'Istodax' },
  { generic: 'Roxithromycin (KR)', brand: 'Rulide and others' },
  { generic: 'Rucaparib (PR)', brand: 'Rubraca' },
  { generic: 'Salmeterol (SR)', brand: 'Serevent and others' },
  { generic: 'Saquinavir (with ritonavir) (PR)', brand: 'Invirase' },
  { generic: 'Selpercatinib (PR)', brand: 'Retevmo' },
  { generic: 'Serdexmethylphenidate (SR)', brand: 'Azstarys' },
  { generic: 'Sertindole (KR)', brand: 'Serdolect and others' },
  { generic: 'Sertraline (CR)', brand: 'Zoloft and others' },
  { generic: 'Sevoflurane (KR)', brand: 'Ultane and others' },
  { generic: 'Sibutramine (SR)', brand: 'Meridia' },
  { generic: 'Siponimod (PR)', brand: 'Mayzent' },
  { generic: 'Sitafloxacin (PR)', brand: 'Gracevit' },
  { generic: 'Solifenacin (CR)', brand: 'Vesicare' },
  { generic: 'Sorafenib (PR)', brand: 'Nexavar' },
  { generic: 'Sotalol (KR)', brand: 'Betapace and others' },
  { generic: 'Sparfloxacin (KR)', brand: 'Zagam' },
  { generic: 'Sulfamethoxazole and Trimethoprim (SR)', brand: 'Septra and others' },
  { generic: 'Sulpiride (KR)', brand: 'Dogmatil and others' },
  { generic: 'Sultopride (KR)', brand: 'Barnetil and others' },
  { generic: 'Sunitinib (PR)', brand: 'Sutent' },
  { generic: 'Tacrolimus (PR)', brand: 'Prograf and others' },
  { generic: 'Tamoxifen (PR)', brand: 'Nolvadex and others' },
  { generic: 'Tazemetostat (PR)', brand: 'Tazverik' },
  { generic: 'Tebentafusp (PR)', brand: 'Kimmtrak' },
  { generic: 'Telaprevir (CR)', brand: 'Incivo and others' },
  { generic: 'Telavancin (PR)', brand: 'Vibativ' },
  { generic: 'Telithromycin (PR)', brand: 'Ketek' },
  { generic: 'Terbutaline (SR)', brand: 'Brethine and others' },
  { generic: 'Terfenadine (KR)', brand: 'Seldane' },
  { generic: 'Terlipressin (KR)', brand: 'Teripress and others' },
  { generic: 'Terodiline (KR)', brand: 'Micturin and others' },
  { generic: 'Tetrabenazine (PR)', brand: 'Nitoman and others' },
  { generic: 'Thioridazine (KR)', brand: 'Mellaril and others' },
  { generic: 'Tiapride (PR)', brand: 'Tiapridal and others' },
  { generic: 'Tipiracil/Trifluridine (PR)', brand: 'Lonsurf' },
  { generic: 'Tizanidine (PR)', brand: 'Zanaflex and others' },
  { generic: 'Tolterodine (PR)', brand: 'Detrol and others' },
  { generic: 'Toremifene (PR)', brand: 'Fareston' },
  { generic: 'Torsemide (Torasemide) (CR)', brand: 'Demadex and others' },
  { generic: 'Tramadol (PR)', brand: 'Crispin and others' },
  { generic: 'Trazodone (CR)', brand: 'Desyrel and others' },
  { generic: 'Triclabendazole (PR)', brand: 'Egaten' },
  { generic: 'Trimipramine (PR)', brand: 'Surmontil and others' },
  { generic: 'Tropisetron (PR)', brand: 'Navoban and others' },
  { generic: 'Valbenazine (PR)', brand: 'Ingrezza' },
  { generic: 'Vandetanib (KR)', brand: 'Caprelsa' },
  { generic: 'Vardenafil (PR)', brand: 'Levitra' },
  { generic: 'Vemurafenib (PR)', brand: 'Zelboraf' },
  { generic: 'Venlafaxine (PR)', brand: 'Effexor and others' },
  { generic: 'Vernakalant (PR)', brand: 'Brinavess and others' },
  { generic: 'Vilanterol/fluticasone furoate (SR)', brand: 'Breo Ellipta' },
  { generic: 'Voclosporin (PR)', brand: 'Lupkynis' },
  { generic: 'Voriconazole (CR)', brand: 'VFend' },
  { generic: 'Vorinostat (PR)', brand: 'Zolinza' },
  { generic: 'Xylometazoline (Xylomethazoline) (SR)', brand: 'Sinosil and others' },
  { generic: 'Ziprasidone (CR)', brand: 'Geodon and others' },
  { generic: 'Zotepine (PR)', brand: 'Losizopilon and others' },
  { generic: 'Zuclopenthixol (Zuclopentixol) (PR)', brand: 'Cisordinol and others' },
];